"use client";

import { FormEvent, useState } from "react";
import type { Lead } from "@/lib/leads";
import type { Testimonial } from "@/lib/testimonials";

export function AdminCommunications({ initialTestimonials, leads }: { initialTestimonials: Testimonial[]; leads: Lead[] }) {
  const [testimonials, setTestimonials] = useState(initialTestimonials); const [quote, setQuote] = useState(""); const [name, setName] = useState(""); const [role, setRole] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState("");
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setMessage(""); try { const response = await fetch("/api/testimonials", { method: "POST", headers: { "Content-Type": "application/json", "x-admin-password": password }, body: JSON.stringify({ quote, name, role }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Could not add testimonial."); setTestimonials([...testimonials, result]); setQuote(""); setName(""); setRole(""); setPassword(""); setMessage("Added to the looping testimonial rail."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not add testimonial."); } };
  return <><section id="testimonials" className="admin-panel"><div className="admin-panel-heading"><div><p>Client testimonials</p><h2>Keep the good words moving.</h2></div><span>{testimonials.length} live</span></div><form className="testimonial-form" onSubmit={submit}><label>Client quote<textarea required rows={3} value={quote} onChange={(event) => setQuote(event.target.value)} /></label><div><label>Name<input required value={name} onChange={(event) => setName(event.target.value)} /></label><label>Role or company<input value={role} onChange={(event) => setRole(event.target.value)} /></label></div><div className="admin-form-footer"><label className="admin-password">Admin password<input required type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label><small>{message}</small><button type="submit">Add testimonial →</button></div></form></section><section id="inbox" className="admin-panel"><div className="admin-panel-heading"><div><p>Contact inbox</p><h2>Recent messages.</h2></div><span>{leads.length} received</span></div><div className="admin-projects">{leads.length ? leads.map((lead) => <article key={`${lead.email}-${lead.createdAt}`}><span className="admin-project-swatch">@</span><div><strong>{lead.name} · {lead.email}</strong><small>{lead.message}</small></div><time>{new Date(lead.createdAt).toLocaleDateString()}</time></article>) : <p className="project-success">No messages yet — the new contact form will land them here.</p>}</div></section></>;
}
